host scan service terminated adn rcp-dir bug fixed

diff --git a/etc/init.d/host-scan b/etc/init.d/host-scan
--- a/etc/init.d/host-scan
+++ b/etc/init.d/host-scan
@@ -28,7 +28,7 @@ SCRIPTNAME=/etc/init.d/$NAME
 [ -x "$DAEMON" ] || exit 0
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+[ -r /etc/nettenance/$NAME.conf ] && . /etc/nettenance/$NAME.conf
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -47,7 +47,8 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	setsid "$DAEMON" > /dev/null
+	[ -f "$PIDFILE" ] && return 1
+	setsid "$DAEMON" > /dev/null || return 2
 }
 
 #
@@ -55,9 +56,15 @@ do_start()
 #
 do_stop()
 {
-	kill $(cat "$PIDFILE")
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	[ -f "$PIDFILE" ] || return 1
+	kill $(cat "$PIDFILE") || return 2
 	# Despite not necessary, kill all running instances
-	pkill "$NAME"
+	pkill "$NAME" &> /dev/null
 }
 
 #
@@ -106,12 +113,25 @@ case "$1" in
 	#
 	log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
-	do_start
+	case "$?" in
+	  0|1)
+	    do_start
+	    case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
 
   *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
 	exit 3
 	;;
 esac
