copy-credentials unstable

diff --git a/usr/sbin/copy-credentials b/usr/sbin/copy-credentials
--- a/usr/sbin/copy-credentials
+++ b/usr/sbin/copy-credentials
@@ -76,7 +76,7 @@ EXAMPLE: $NTT_CMD_NAME
 EOF
 }
 
-hostfile=userhost.lst
+hostfile="userhost.lst"
 
 # ask a password
 # $1: User notification
@@ -119,9 +119,10 @@ while true ; do
             *) identity=$2 ; shift 2 ;;
         esac ;;
         --) shift ; break ;;
-        *) echo "Internal error!" >&2; exit 1 ;;
+        *) echo "Internal error!" >&2; exit 1 ;; 
     esac
 done
+
 
 hostfile=$(look_for $hostfile HOST)
 check_existence_of $hostfile
